services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn mycurrency.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - /mycurrency/.env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis_broker
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A mycurrency worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - /mycurrency/.env
    depends_on:
      - redis
